export const features: Feature[] = [
  {
    label: "Bold text",
    slug: "bold-text",
    type: "formatting",
    rssTag: "<strong>",
    description: "Make text bold.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Italic text",
    slug: "italic-text",
    type: "formatting",
    rssTag: "<em>",
    description: "Make text italic.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Underlined text",
    slug: "underlined-text",
    type: "formatting",
    rssTag: "<u>",
    description: "Make text underlined.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Strikethrough text",
    slug: "strikethrough-text",
    type: "formatting",
    rssTag: "<s>",
    description: "Make text strikethrough.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Hyperlink",
    slug: "hyperlink",
    type: "formatting",
    rssTag: "<a>",
    description: "Add a hyperlink.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Image",
    slug: "image",
    type: "formatting",
    rssTag: "<img>",
    description: "Add an image.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Bulleted List",
    slug: "bulleted-list",
    type: "formatting",
    rssTag: "<ul><li>",
    description: "Create a bulleted list.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Numbered List",
    slug: "numbered-list",
    type: "formatting",
    rssTag: "<ol><li>",
    description: "Create a numbered list.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Blockquote",
    slug: "blockquote",
    type: "formatting",
    rssTag: "<blockquote>",
    description: "Create a blockquote.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Code",
    slug: "code",
    type: "formatting",
    rssTag: "<code>",
    description: "Add code.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Horizontal Rule",
    slug: "horizontal-rule",
    type: "formatting",
    rssTag: "<hr>",
    description: "Create a horizontal rule.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Headings",
    slug: "heading",
    type: "formatting",
    rssTag: "<h1>, <h2>, <h3>, <h4>, <h5>, <h6>",
    description: "Create a heading.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Paragraph",
    slug: "paragraph",
    type: "formatting",
    rssTag: "<p>",
    description: "Create a paragraph.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Line Break",
    slug: "line-break",
    type: "formatting",
    rssTag: "<br>",
    description: "Create a line break.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Hashtags",
    slug: "hashtags",
    type: "metadata",
    rssTag: "#hashtag",
    description: "Add hashtags to your content.",
    parents: ["<description>", "<itunes:summary>", "<content:encoded>"],
  },
  {
    label: "Podcast Ratings",
    slug: "podcast-ratings",
    type: "interactivity",
    description: "Audience ratings for the podcast (usually 1&ndash;5 stars)",
    parents: ["podcast"],
  },
  {
    label: "Podcast Reviews",
    slug: "podcast-reviews",
    type: "interactivity",
    description: "Audience reviews for the podcast",
    parents: ["podcast"],
  },
]

export default features
